import { sitePath } from './site-path.js';
export const locales = ['es'];
export const image = (id, width = 2400) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=90`;
export const photos = {
  hero: image('photo-1600210492486-724fe5c67fb0'),
  architecture: image('photo-1487958449943-2429e8be8625'),
  interior: image('photo-1600607687920-4e2a09cf159d'),
  workplace: image('photo-1497366811353-6870744d04b2'),
  team: image('photo-1524758631624-e2822e304c36'),
  detail: image('photo-1616486338812-3dadae4b4ace'),
};
export const projects = [
  { slug: 'the-olive-house', image: photos.hero, type: 'residential', year: '2025', area: '320 m²', es: { title: 'Zeytin Evi', place: 'Urla, İzmir', tag: 'Konut · İç mimari', intro: 'Ege’nin ışığı ve doğasıyla şekillenen, daha sakin bir yaşam biçimi.', challenge: 'Bahçeyle güçlü bir ilişki kuran, en sıcak aylarda da mahremiyet ve serinlik sağlayan ferah bir aile evi tasarlamak.', approach: 'Ortak yaşam alanlarını gölgeli bir avlu etrafında kurguladık. Meşe doğramalar, kireç badanalı duvarlar ve yerel taş sade bir malzeme paleti oluştururken derin pencere açıklıkları öğleden sonra ışığını yumuşatıyor.', outcome: 'İç ve dış mekân arasında doğal bir geçiş sağlayan bir ev ortaya çıktı. Esnek yaşam alanları hem ailenin günlük rutinine hem de arkadaşlarla geçirilen hafta sonlarına uyum sağlıyor.' } },
  { slug: 'common-ground', image: photos.workplace, type: 'workplace', year: '2025', area: '1,200 m²', es: { title: 'Ortak Zemin', place: 'Karaköy, İstanbul', tag: 'Çalışma alanı · Mekânsal strateji', intro: 'Odaklanmadan ödün vermeden insanları buluşturan, değişime açık bir çalışma alanı.', challenge: 'Geleneksel bir ofis katını, farklı çalışma alışkanlıklarına sahip büyüyen bir ekip için davetkâr bir ortama dönüştürmek.', approach: 'Planın merkezine sosyal bir alan yerleştirdik; çevresini sessiz odalar ve esnek ekip alanlarıyla tamamladık. Bitkiler ve doğal malzemeler geleneksel ofis ortamına daha yumuşak bir alternatif sunuyor.', outcome: 'Ortak ve bireysel alanlar arasındaki denge, ekibe büyük bir yenilemeye ihtiyaç duymadan iş birliği yapma, odaklanma ve gelişme imkânı veriyor.' } },
  { slug: 'a-still-retreat', image: photos.interior, type: 'hospitality', year: '2024', area: '860 m²', es: { title: 'Sakin Bir Mola', place: 'Bodrum, Muğla', tag: 'Konaklama · İç mimari', intro: 'Bulunduğu yere ait hissettiren, yalın dokunuşlarla şekillenmiş küçük bir kıyı oteli.', challenge: 'Butik bir konukevine, mahallenin sakin karakterini koruyarak kendine özgü bir kimlik kazandırmak.', approach: 'Taş yüzeyler, dokuma ayırıcılar ve özel mobilyalar için yerel ustalarla çalıştık. Dolaşım alanlarını küçük açık hava mekânlarına bağlayarak yolculuğu da varış noktası kadar özenli kurguladık.', outcome: 'Sıcak ve dayanıklı iç mekânlar, kıyıyı keşfetmek isteyen konuklara sakin bir başlangıç sunuyor. Tutarlı malzeme dili odaları, salonu ve avluyu birbirine bağlıyor.' } },
  { slug: 'courtyard-living', image: photos.architecture, type: 'residential', year: '2024', area: '480 m²', es: { title: 'Avluda Yaşam', place: 'Çeşme, İzmir', tag: 'Konut · Mimari', intro: 'Gökyüzünü çerçeveleyen ve günlük ritüellere alan açan çağdaş bir ev.', challenge: 'Kompakt bir arsada, komşu yapıların mahremiyetini korurken bol gün ışığı alan bir ev tasarlamak.', approach: 'İki yalın kütle açık bir avluyu çevreliyor. Açıklıklar manzarayı çerçevelemek, ışığı içeri almak ve çapraz havalandırmayı sağlamak için özenle konumlandırıldı; korunaklı teras yaşam alanını genişletiyor.', outcome: 'İçe dönük plan, beklenmedik ölçüde açık bir ev oluşturuyor. Avlu, mevsimlere ve güneşin hareketine göre değişen günlük yaşamın merkezi hâline geliyor.' } },
];
export const articles = [
  { slug: 'designing-for-the-everyday', image: photos.interior, date: '2026-05-14', es: { category: 'Bakış açısı', title: 'İyi tasarım, günlük yaşamla başlar.', excerpt: 'En küçük günlük ritüeller neden en anlamlı tasarım kararlarına yol açar?', read: '4 dk okuma', sections: [['Çizimden önce bir günü düşünün', 'Bir oda çizmeden önce, o odada bir günün nasıl geçtiğini sorarız. Sabah ışığı nereye düşüyor? Çantalar nereye bırakılıyor? İnsanlar ne zaman bir arada olmaya, ne zaman kendilerine ait bir alana ihtiyaç duyuyor? Bu sıradan sorular projeye yön verir.'], ['Gerçek yaşama alan açın', 'Güzel bir iç mekânda yaşamak da kolay olmalıdır. Depolama ihtiyaç duyulan yerde olmalı, dolaşım sezgisel hissettirmeli ve mobilyalar birden fazla kullanımı desteklemelidir. Esneklik, insanların gerçekten ne yaptığını anlamakla başlar.'], ['Detayların işini yapmasına izin verin', 'Rahat bir pencere önü oturma alanı, doğru konumlanmış bir ışık veya geniş bir eşik, bir mekânın deneyimini değiştirebilir. Bu sessiz müdahalelere değer veriyoruz; çünkü ilk izlenim geçtikten çok sonra bile işlevlerini sürdürürler.']] } },
  { slug: 'materials-that-age-well', image: photos.detail, date: '2026-04-22', es: { category: 'Malzemeler', title: 'Zamanla güzelleşen malzemeler.', excerpt: 'Doğal yüzeylere, özgün dokulara ve kalıcı karaktere özenli bir yaklaşım.', read: '3 dk okuma', sections: [['Kusursuzluk yerine karakteri seçin', 'Ahşap patina kazanır, taş kendi çeşitliliğini gösterir ve doğal kumaşlar kullanıldıkça yumuşar. Bunlar gizlenecek kusurlar değildir. Mekânın yaşanmış hissettirmesine ve kullanıcılarıyla bağ kurmasına yardımcı olurlar.'], ['Bakımı en baştan düşünün', 'Malzeme seçimi aynı zamanda pratik bir karardır. Bir yüzey belirlemeden önce müşterilerimizle temizlik, onarım ve yenileme konularını konuşuruz. Kullanımına ve bakım rutinine uygun bir yüzey daha uzun süre kullanılabilir.'], ['Sade bir palet oluşturun', 'Birbirini tamamlayan birkaç malzeme, uzun bir yüzey listesinden daha fazla derinlik sunabilir. Bir dokuyu veya tonu odalar arasında tekrarlamak süreklilik yaratır; ışık ve oranın kompozisyonun parçası olmasına imkân verir.']] } },
  { slug: 'a-better-place-to-work', image: photos.workplace, date: '2026-03-10', es: { category: 'Çalışma alanı', title: 'En iyi işiniz için daha iyi bir yer.', excerpt: 'Bağ kurma, odaklanma ve biraz nefes alma alanı arasında denge kurmak.', read: '5 dk okuma', sections: [['Tek ofis, farklı çalışma biçimleri', 'Ekipler gün boyunca sohbet, odaklanmış görevler ve doğaçlama problem çözme arasında geçiş yapar. Tek tip bir çalışma alanı bunların hepsini nadiren destekler. Masa yerleştirmek yerine faaliyetleri haritalayarak başlarız.'], ['İnsanlara seçim sunun', 'Sessiz odaların, ortak masaların ve rahat sosyal alanların her birinin bir rolü vardır. Net akustik ayrım ve alanlar arasında kolay geçiş, insanların başkalarını rahatsız etmeden görevlerine uygun yeri seçmesine yardımcı olur.'], ['Dışarıyı yaklaştırın', 'Gün ışığı, manzara ve bitkilendirilmiş alanlar çalışma ortamını daha keyifli kılabilir. Bunları sonradan eklenen süslemeler yerine mekânsal planın parçası olarak ele alır, doğal ışığı parlama kontrolü ve konforla dengeleriz.']] } },
];

export const copy = {
 es: {
  nav: ['Inicio','Estudio','Servicios','Proyectos','Cursos','Contacto'], start: 'Hablemos de tu proyecto', explore: 'Ver proyectos', allProjects: 'Ver todos los proyectos', allServices: 'Ver todos los servicios', allInsights: 'Ver cursos', back: 'Volver', skip: 'Ir al contenido', menu: 'Abrir menú', close: 'Cerrar menú',
  home: { eyebrow: 'DISEÑO · PLANOS · FORMACIÓN', title: 'Arquitectura que empieza con una idea.', intro: 'Diseño, planos y formación con atención directa de la Arq. Diana G. Piñanez, desde la primera idea hasta cada detalle.', imageLabel: 'ARQ. DIANA G. PIÑANEZ', imageLocation: 'Paraguay', scroll: 'Conocé el estudio', introLabel: 'ESTUDIO DE ARQUITECTURA', introTitle: 'Tu idea puede convertirse\nen un espacio real.', introText: 'Cada proyecto parte de escuchar lo que necesitás. Diseñamos espacios, desarrollamos planos y compartimos herramientas para que tus ideas puedan avanzar con claridad.', introLink: 'Conocé el estudio', serviceLabel: 'SERVICIOS', serviceTitle: 'Tres formas de\ntrabajar juntos.', serviceText: 'Diseño, planos y formación para distintas necesidades.', projectLabel: 'TRABAJOS REALIZADOS', projectTitle: 'Diseño pensado\npara cada espacio.', projectText: 'Una selección de proyectos desarrollados con atención al detalle.', quote: '“Cada espacio debe responder a quien lo va a vivir.”', quoteName: 'Arq. Diana G. Piñanez', quoteRole: 'Arquitecta', journalLabel: 'CURSOS', journalTitle: 'Aprendé con Diana.', journalText: 'Cursos y capacitaciones prácticas para incorporar herramientas de arquitectura y diseño.' },
  stats: [['01','Atención directa con la arquitecta'],['03','Líneas de trabajo'],['100%','Diseño personalizado'],['PY','Proyectos en Paraguay']],
  about: { eyebrow: 'EL ESTUDIO', title: 'Arq. Diana G. Piñanez', intro: 'Arquitectura cercana, funcional y pensada para las personas.', storyTitle: 'Diseño con intención.\nAcompañamiento directo.', story: ['El estudio acompaña proyectos residenciales desde la idea inicial hasta su definición, combinando funcionalidad, estética y necesidades reales.','También desarrolla reformas, ampliaciones, mobiliario y documentación para planos municipales.'], valuesLabel: 'FORMA DE TRABAJO', valuesTitle: 'Cada proyecto es diferente.', values: [['Escuchar primero','Entender tus necesidades es el punto de partida.'],['Diseñar con propósito','Cada decisión busca resolver una necesidad real.'],['Acompañamiento directo','Contacto cercano durante las distintas etapas.']], teamLabel: 'ARQUITECTA', teamTitle: 'Una mirada personal para cada proyecto.', team: [['Diana G. Piñanez','Arquitecta','Diseño arquitectónico, reformas, ampliaciones, mobiliario y planos municipales.']] },
  services: { eyebrow: 'SERVICIOS', title: 'Diseño, planos\ny formación.', intro: 'Tres líneas de trabajo, pensadas para necesidades diferentes.', items: [['Diseño','De la idea al proyecto.','Diseño arquitectónico para viviendas, reformas, ampliaciones y soluciones de mobiliario, con una propuesta adaptada a cada necesidad.',['Diseño arquitectónico','Viviendas','Reformas y ampliaciones','Mobiliario y detalles']],['Planos','Documentación para avanzar.','Desarrollo y organización de planos y documentación técnica para acompañar correctamente cada proyecto.',['Relevamiento','Documentación gráfica','Planos municipales','Asesoramiento técnico']],['Cursos y capacitaciones','Aprendé herramientas que podés aplicar.','Formación práctica para estudiantes, profesionales y personas que buscan incorporar herramientas de arquitectura y diseño.',['Cursos de diseño','Capacitaciones prácticas','Herramientas digitales','Modalidades según necesidad']]], processLabel: 'CÓMO TRABAJAMOS', processTitle: 'Un proceso simple y claro.', steps: [['Conversamos','Nos contás qué necesitás y qué querés lograr.'],['Proponemos','Definimos una dirección de diseño.'],['Desarrollamos','Trabajamos planos, detalles y materiales.'],['Entregamos','Presentamos el proyecto de forma clara.']], faqTitle: 'Preguntas frecuentes', faqs: [['¿Puedo consultar aunque todavía no tenga definido el proyecto?','Sí. La primera conversación sirve para entender tu idea y orientarte sobre el servicio que mejor se adapta a lo que necesitás.'],['¿Trabajan con planos?','Sí. Desarrollamos y organizamos la documentación necesaria según cada proyecto.'],['¿También realizan cursos y capacitaciones?','Sí. Hay propuestas formativas y capacitaciones prácticas según el tema y la necesidad.']] },
  projects: { eyebrow: 'PROYECTOS', title: 'Trabajos entregados.', intro: 'Proyectos de arquitectura e interiorismo con una mirada funcional y personalizada.', filters: ['Todos','Residencial','Interiores','Mobiliario'], count: 'proyectos', challenge: 'El desafío', approach: 'La propuesta', outcome: 'El resultado', location: 'Ubicación', year: 'Año', area: 'Superficie', next: 'Ver otro proyecto', disclaimer: 'Las imágenes actuales son temporales hasta incorporar el portfolio real del estudio.' },
  insights: { eyebrow: 'CURSOS Y CAPACITACIONES', title: 'Aprendé herramientas\nque podés aplicar.', intro: 'Formación práctica en arquitectura y diseño, con contenidos pensados para estudiantes, profesionales y personas que quieren aprender.', read: 'Ver contenido', by: 'Arq. Diana G. Piñanez', more: 'Más contenidos' },
  contact: { eyebrow: 'CONTACTO DIRECTO', title: 'Contame qué necesitás\ny vemos cómo ayudarte.', intro: 'Diseño, planos, cursos o capacitaciones.', studio: 'Estudio', place: 'Paraguay', hours: 'Atención con coordinación previa', visit: 'Consultas y reuniones con coordinación previa.', formTitle: 'Hablemos.', formIntro: 'Dejá tus datos y contame brevemente qué necesitás.', name: 'Nombre y apellido', email: 'Correo electrónico', phone: 'Teléfono', subject: '¿Qué necesitás?', message: 'Mensaje', placeholder: 'Contame sobre tu proyecto o curso de interés', submit: 'Enviar consulta', note: 'Próximamente conectaremos este formulario con el canal de contacto del estudio.', success: 'Gracias por tu consulta.', successText: 'Recibimos los datos del formulario.', edit: 'Editar mensaje', direct: 'Contacto directo', directText: 'Consultá por diseño, planos, cursos o capacitaciones.' },
  cta: { label: '¿TENÉS UN PROYECTO EN MENTE?', title: 'Hagamos espacio\npara tu idea.', text: 'Contame qué necesitás y coordinamos una primera conversación.' },
  footer: { description: 'Arq. Diana G. Piñanez\nEstudio de arquitectura en Paraguay.', explore: 'Explorar', find: 'Ubicación', location: 'Paraguay', note: '© 2026 Arq. Diana G. Piñanez. Todos los derechos reservados.', privacy: 'Privacidad', privacyTitle: 'Privacidad', privacyText: 'Sitio web oficial del estudio de la Arq. Diana G. Piñanez.' },
  notFound: { title: 'Esta página no está disponible.', text: 'Volvé al inicio para seguir navegando.', button: 'Volver al inicio' }
 }
};
export const paths = ['', '/about', '/services', '/projects', '/insights', '/contact'];
export function pageMetadata(locale, index) {
 const c = copy[locale] || copy.es;
 return { title: `${c.nav[index]} | Arq. Diana G. Piñanez`, description: [c.home.intro,c.about.intro,c.services.intro,c.projects.intro,c.insights.intro,c.contact.intro][index], alternates: { languages: { es: sitePath(`/es${paths[index]}/`) } } };
}
