import { sitePath } from './site-path.js';
export const locales = ['es'];
export const image = (id, width = 2400) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=90`;
export const photos = {
  hero: image('photo-1600210492486-724fe5c67fb0'),
  architecture: image('photo-1487958449943-2429e8be8625'),
  interior: image('photo-1600607687920-4e2a09cf159d'),
  workplace: image('photo-1497366811353-6870744d04b2'),
  team: image('photo-1524758631624-e2822e304c36'),
  detail: image('photo-1616486338812-3dadae4b4ace'),
};
export const projects = [
  { slug: 'the-olive-house', image: photos.hero, type: 'residential', year: '2025', area: '320 m²', en: { title: 'The Olive House', place: 'Urla, İzmir', tag: 'Residential · Interior design', intro: 'A quieter way of living, shaped by the light and landscape of the Aegean.', challenge: 'Create a generous family home that feels connected to its garden, while offering privacy and shelter during the hottest months.', approach: 'We organised shared spaces around a shaded courtyard. Oak joinery, limewashed walls, and local stone bring a restrained palette to life; deep window reveals soften the afternoon light.', outcome: 'The result is a home that moves naturally between indoors and outdoors. Flexible living areas accommodate both everyday family life and weekends with friends.' }, tr: { title: 'Zeytin Evi', place: 'Urla, İzmir', tag: 'Konut · İç mimari', intro: 'Ege’nin ışığı ve doğasıyla şekillenen, daha sakin bir yaşam biçimi.', challenge: 'Bahçeyle güçlü bir ilişki kuran, en sıcak aylarda da mahremiyet ve serinlik sağlayan ferah bir aile evi tasarlamak.', approach: 'Ortak yaşam alanlarını gölgeli bir avlu etrafında kurguladık. Meşe doğramalar, kireç badanalı duvarlar ve yerel taş sade bir malzeme paleti oluştururken derin pencere açıklıkları öğleden sonra ışığını yumuşatıyor.', outcome: 'İç ve dış mekân arasında doğal bir geçiş sağlayan bir ev ortaya çıktı. Esnek yaşam alanları hem ailenin günlük rutinine hem de arkadaşlarla geçirilen hafta sonlarına uyum sağlıyor.' } },
  { slug: 'common-ground', image: photos.workplace, type: 'workplace', year: '2025', area: '1,200 m²', en: { title: 'Common Ground', place: 'Karaköy, İstanbul', tag: 'Workplace · Spatial strategy', intro: 'An adaptable workplace that brings people together without compromising focus.', challenge: 'Transform a conventional office floor into a welcoming environment for a growing team with different ways of working.', approach: 'A central social space anchors the plan, with quiet rooms and flexible team areas around its edges. Planting and natural materials provide a softer alternative to the traditional office.', outcome: 'A clear balance of shared and individual settings gives the team room to collaborate, concentrate, and evolve without another major fit-out.' }, tr: { title: 'Ortak Zemin', place: 'Karaköy, İstanbul', tag: 'Çalışma alanı · Mekânsal strateji', intro: 'Odaklanmadan ödün vermeden insanları buluşturan, değişime açık bir çalışma alanı.', challenge: 'Geleneksel bir ofis katını, farklı çalışma alışkanlıklarına sahip büyüyen bir ekip için davetkâr bir ortama dönüştürmek.', approach: 'Planın merkezine sosyal bir alan yerleştirdik; çevresini sessiz odalar ve esnek ekip alanlarıyla tamamladık. Bitkiler ve doğal malzemeler geleneksel ofis ortamına daha yumuşak bir alternatif sunuyor.', outcome: 'Ortak ve bireysel alanlar arasındaki denge, ekibe büyük bir yenilemeye ihtiyaç duymadan iş birliği yapma, odaklanma ve gelişme imkânı veriyor.' } },
  { slug: 'a-still-retreat', image: photos.interior, type: 'hospitality', year: '2024', area: '860 m²', en: { title: 'A Still Retreat', place: 'Bodrum, Muğla', tag: 'Hospitality · Interior design', intro: 'A small coastal retreat with a strong sense of place and a light touch.', challenge: 'Give a boutique guesthouse a distinctive identity while retaining the unhurried character of its neighbourhood.', approach: 'We worked with local makers on stone surfaces, woven screens, and bespoke furniture. Circulation opens onto small outdoor rooms, making the journey as considered as the destination.', outcome: 'Warm, durable interiors offer guests a calm base from which to discover the coast. A consistent material language connects the bedrooms, lounge, and courtyard.' }, tr: { title: 'Sakin Bir Mola', place: 'Bodrum, Muğla', tag: 'Konaklama · İç mimari', intro: 'Bulunduğu yere ait hissettiren, yalın dokunuşlarla şekillenmiş küçük bir kıyı oteli.', challenge: 'Butik bir konukevine, mahallenin sakin karakterini koruyarak kendine özgü bir kimlik kazandırmak.', approach: 'Taş yüzeyler, dokuma ayırıcılar ve özel mobilyalar için yerel ustalarla çalıştık. Dolaşım alanlarını küçük açık hava mekânlarına bağlayarak yolculuğu da varış noktası kadar özenli kurguladık.', outcome: 'Sıcak ve dayanıklı iç mekânlar, kıyıyı keşfetmek isteyen konuklara sakin bir başlangıç sunuyor. Tutarlı malzeme dili odaları, salonu ve avluyu birbirine bağlıyor.' } },
  { slug: 'courtyard-living', image: photos.architecture, type: 'residential', year: '2024', area: '480 m²', en: { title: 'Courtyard Living', place: 'Çeşme, İzmir', tag: 'Residential · Architecture', intro: 'A contemporary home that frames the sky and makes room for daily rituals.', challenge: 'Design a home on a compact site that offers generous daylight without overlooking neighbouring properties.', approach: 'Two simple volumes wrap an open courtyard. Openings are carefully placed to frame views, draw in light, and enable cross-ventilation; a sheltered terrace extends the living area.', outcome: 'An inward-looking plan creates a surprisingly open home. The courtyard becomes the centre of everyday life, changing with the seasons and the movement of the sun.' }, tr: { title: 'Avluda Yaşam', place: 'Çeşme, İzmir', tag: 'Konut · Mimari', intro: 'Gökyüzünü çerçeveleyen ve günlük ritüellere alan açan çağdaş bir ev.', challenge: 'Kompakt bir arsada, komşu yapıların mahremiyetini korurken bol gün ışığı alan bir ev tasarlamak.', approach: 'İki yalın kütle açık bir avluyu çevreliyor. Açıklıklar manzarayı çerçevelemek, ışığı içeri almak ve çapraz havalandırmayı sağlamak için özenle konumlandırıldı; korunaklı teras yaşam alanını genişletiyor.', outcome: 'İçe dönük plan, beklenmedik ölçüde açık bir ev oluşturuyor. Avlu, mevsimlere ve güneşin hareketine göre değişen günlük yaşamın merkezi hâline geliyor.' } },
];
export const articles = [
  { slug: 'designing-for-the-everyday', image: photos.interior, date: '2026-05-14', en: { category: 'Perspective', title: 'Good design starts with the everyday.', excerpt: 'Why the smallest daily rituals often lead to the most meaningful design decisions.', read: '4 min read', sections: [['Start with a day, not a drawing', 'Before we sketch a room, we ask how a day unfolds within it. Where does the morning light land? Where do bags get dropped? When do people need to be together, and when do they need a little space? These ordinary questions give a project its direction.'], ['Make space for real life', 'A beautiful interior should also be easy to live with. Storage belongs where it is needed, circulation should feel intuitive, and furniture should support more than one way of using a room. Flexibility begins with understanding what people actually do.'], ['Let the details do the work', 'A comfortable window seat, a well-placed light, or a generous threshold can change the experience of a space. We value these quiet interventions because they keep working long after the first impression has faded.']] }, tr: { category: 'Bakış açısı', title: 'İyi tasarım, günlük yaşamla başlar.', excerpt: 'En küçük günlük ritüeller neden en anlamlı tasarım kararlarına yol açar?', read: '4 dk okuma', sections: [['Çizimden önce bir günü düşünün', 'Bir oda çizmeden önce, o odada bir günün nasıl geçtiğini sorarız. Sabah ışığı nereye düşüyor? Çantalar nereye bırakılıyor? İnsanlar ne zaman bir arada olmaya, ne zaman kendilerine ait bir alana ihtiyaç duyuyor? Bu sıradan sorular projeye yön verir.'], ['Gerçek yaşama alan açın', 'Güzel bir iç mekânda yaşamak da kolay olmalıdır. Depolama ihtiyaç duyulan yerde olmalı, dolaşım sezgisel hissettirmeli ve mobilyalar birden fazla kullanımı desteklemelidir. Esneklik, insanların gerçekten ne yaptığını anlamakla başlar.'], ['Detayların işini yapmasına izin verin', 'Rahat bir pencere önü oturma alanı, doğru konumlanmış bir ışık veya geniş bir eşik, bir mekânın deneyimini değiştirebilir. Bu sessiz müdahalelere değer veriyoruz; çünkü ilk izlenim geçtikten çok sonra bile işlevlerini sürdürürler.']] } },
  { slug: 'materials-that-age-well', image: photos.detail, date: '2026-04-22', en: { category: 'Materials', title: 'Materials that get better with time.', excerpt: 'A considered approach to natural finishes, honest textures, and lasting character.', read: '3 min read', sections: [['Choose character over perfection', 'Timber develops a patina, stone reveals its variation, and natural textiles soften with use. These changes are not flaws to hide. They help a space feel lived in and connected to the people who use it.'], ['Consider care from the beginning', 'Material selection is also a practical decision. We discuss cleaning, repair, and replacement with clients before specifying a finish. A surface that fits its setting and maintenance routine is more likely to stay in use.'], ['Build a restrained palette', 'A few complementary materials can provide more depth than a long list of finishes. Repeating a texture or tone across rooms creates continuity, allowing light and proportion to become part of the composition.']] }, tr: { category: 'Malzemeler', title: 'Zamanla güzelleşen malzemeler.', excerpt: 'Doğal yüzeylere, özgün dokulara ve kalıcı karaktere özenli bir yaklaşım.', read: '3 dk okuma', sections: [['Kusursuzluk yerine karakteri seçin', 'Ahşap patina kazanır, taş kendi çeşitliliğini gösterir ve doğal kumaşlar kullanıldıkça yumuşar. Bunlar gizlenecek kusurlar değildir. Mekânın yaşanmış hissettirmesine ve kullanıcılarıyla bağ kurmasına yardımcı olurlar.'], ['Bakımı en baştan düşünün', 'Malzeme seçimi aynı zamanda pratik bir karardır. Bir yüzey belirlemeden önce müşterilerimizle temizlik, onarım ve yenileme konularını konuşuruz. Kullanımına ve bakım rutinine uygun bir yüzey daha uzun süre kullanılabilir.'], ['Sade bir palet oluşturun', 'Birbirini tamamlayan birkaç malzeme, uzun bir yüzey listesinden daha fazla derinlik sunabilir. Bir dokuyu veya tonu odalar arasında tekrarlamak süreklilik yaratır; ışık ve oranın kompozisyonun parçası olmasına imkân verir.']] } },
  { slug: 'a-better-place-to-work', image: photos.workplace, date: '2026-03-10', en: { category: 'Workplace', title: 'A better place to do your best work.', excerpt: 'Finding the balance between connection, concentration, and a little breathing room.', read: '5 min read', sections: [['One office, many ways of working', 'Teams move between conversation, focused tasks, and informal problem-solving throughout the day. A single type of workspace rarely supports all three. We begin by mapping activities rather than assigning desks.'], ['Give people a choice', 'Quiet rooms, shared tables, and comfortable social spaces each have a role. Clear acoustic separation and easy movement between settings help people choose the place that fits the task, without disrupting others.'], ['Bring the outside closer', 'Daylight, views, and planted areas can make a workplace more pleasant to spend time in. We treat them as part of the spatial plan rather than decorations added at the end, balancing natural light with glare control and comfort.']] }, tr: { category: 'Çalışma alanı', title: 'En iyi işiniz için daha iyi bir yer.', excerpt: 'Bağ kurma, odaklanma ve biraz nefes alma alanı arasında denge kurmak.', read: '5 dk okuma', sections: [['Tek ofis, farklı çalışma biçimleri', 'Ekipler gün boyunca sohbet, odaklanmış görevler ve doğaçlama problem çözme arasında geçiş yapar. Tek tip bir çalışma alanı bunların hepsini nadiren destekler. Masa yerleştirmek yerine faaliyetleri haritalayarak başlarız.'], ['İnsanlara seçim sunun', 'Sessiz odaların, ortak masaların ve rahat sosyal alanların her birinin bir rolü vardır. Net akustik ayrım ve alanlar arasında kolay geçiş, insanların başkalarını rahatsız etmeden görevlerine uygun yeri seçmesine yardımcı olur.'], ['Dışarıyı yaklaştırın', 'Gün ışığı, manzara ve bitkilendirilmiş alanlar çalışma ortamını daha keyifli kılabilir. Bunları sonradan eklenen süslemeler yerine mekânsal planın parçası olarak ele alır, doğal ışığı parlama kontrolü ve konforla dengeleriz.']] } },
];

export const copy = {
 es: {
  nav: ['Inicio','Estudio','Servicios','Proyectos','Cursos','Contacto'], start: 'Hablemos de tu proyecto', explore: 'Ver proyectos', allProjects: 'Ver todos los proyectos', allServices: 'Ver todos los servicios', allInsights: 'Ver cursos', back: 'Volver', skip: 'Ir al contenido', menu: 'Abrir menú', close: 'Cerrar menú',
  home: { eyebrow: 'ARQUITECTURA · INTERIORES · MOBILIARIO', title: 'Diseñamos espacios.\nCreamos posibilidades.', intro: 'Arquitectura y diseño con atención directa de la Arq. Diana G. Piñanez, desde la primera idea hasta cada detalle.', imageLabel: 'ARQ. DIANA G. PIÑANEZ', imageLocation: 'Paraguay', scroll: 'Conocé el estudio', introLabel: 'ESTUDIO DE ARQUITECTURA', introTitle: 'Tu idea puede convertirse\nen un espacio real.', introText: 'Cada proyecto parte de escuchar lo que necesitás. Diseñamos viviendas, reformas, ampliaciones y mobiliario buscando equilibrio entre funcionalidad, estética y presupuesto.', introLink: 'Conocé el estudio', serviceLabel: 'SERVICIOS', serviceTitle: '¿Qué proyecto\ntenés en mente?', serviceText: 'Soluciones para empezar, transformar o documentar tu proyecto.', projectLabel: 'TRABAJOS REALIZADOS', projectTitle: 'Diseño pensado\npara cada espacio.', projectText: 'Una selección de proyectos desarrollados con atención al detalle.', quote: '“Cada espacio debe responder a quien lo va a vivir.”', quoteName: 'Arq. Diana G. Piñanez', quoteRole: 'Arquitecta', journalLabel: 'CURSOS', journalTitle: 'Aprendé diseño mobiliario.', journalText: 'Formación práctica para desarrollar muebles desde cero y presentar un proyecto profesionalmente.' },
  stats: [['01','Atención directa con la arquitecta'],['04','Servicios principales'],['100%','Diseño personalizado'],['PY','Proyectos en Paraguay']],
  about: { eyebrow: 'EL ESTUDIO', title: 'Arq. Diana G. Piñanez', intro: 'Arquitectura cercana, funcional y pensada para las personas.', storyTitle: 'Diseño con intención.\nAcompañamiento directo.', story: ['El estudio acompaña proyectos residenciales desde la idea inicial hasta su definición, combinando funcionalidad, estética y necesidades reales.','También desarrolla reformas, ampliaciones, mobiliario y documentación para planos municipales.'], valuesLabel: 'FORMA DE TRABAJO', valuesTitle: 'Cada proyecto es diferente.', values: [['Escuchar primero','Entender tus necesidades es el punto de partida.'],['Diseñar con propósito','Cada decisión busca resolver una necesidad real.'],['Acompañamiento directo','Contacto cercano durante las distintas etapas.']], teamLabel: 'ARQUITECTA', teamTitle: 'Una mirada personal para cada proyecto.', team: [['Diana G. Piñanez','Arquitecta','Diseño arquitectónico, reformas, ampliaciones, mobiliario y planos municipales.']] },
  services: { eyebrow: 'SERVICIOS', title: 'Del primer boceto\na una solución concreta.', intro: 'Elegí el servicio que mejor se adapta a lo que necesitás.', items: [['Diseño de vivienda','Tu casa desde cero.','Diseñamos tu vivienda desde la idea inicial, distribución y concepto hasta una propuesta definida.',['Diseño arquitectónico','Distribución de espacios','Concepto y propuesta visual','Desarrollo del proyecto']],['Reformas y ampliaciones','Transformá lo que ya tenés.','Rediseñamos espacios existentes y estudiamos ampliaciones para adaptarlos a nuevas necesidades.',['Reorganización de espacios','Reformas residenciales','Ampliaciones','Propuesta estética y funcional']],['Diseño de mobiliario','Muebles pensados para tu espacio.','Asesoramiento y diseño de mobiliario personalizado según medidas, uso y estilo.',['Diseño desde cero','Despiece','Definición de materiales','Presentación del diseño']],['Planos municipales','Documentación para tu proyecto.','Preparación y organización de planos municipales según las necesidades del proyecto.',['Relevamiento de información','Documentación gráfica','Planos municipales','Asesoramiento']]], processLabel: 'CÓMO TRABAJAMOS', processTitle: 'Un proceso simple y claro.', steps: [['Conversamos','Nos contás qué necesitás y qué querés lograr.'],['Proponemos','Definimos una dirección de diseño.'],['Desarrollamos','Trabajamos planos, detalles y materiales.'],['Entregamos','Presentamos el proyecto de forma clara.']], faqTitle: 'Preguntas frecuentes', faqs: [['¿Puedo consultar aunque todavía no tenga definido el proyecto?','Sí. La primera conversación sirve para entender tu idea y orientarte.'],['¿Realizan reformas y ampliaciones?','Sí. Analizamos los espacios existentes y desarrollamos una propuesta.'],['¿También diseñan muebles?','Sí. Desarrollamos mobiliario a medida y también contamos con cursos de diseño mobiliario.']] },
  projects: { eyebrow: 'PROYECTOS', title: 'Trabajos entregados.', intro: 'Proyectos de arquitectura e interiorismo con una mirada funcional y personalizada.', filters: ['Todos','Residencial','Interiores','Mobiliario'], count: 'proyectos', challenge: 'El desafío', approach: 'La propuesta', outcome: 'El resultado', location: 'Ubicación', year: 'Año', area: 'Superficie', next: 'Ver otro proyecto', disclaimer: 'Las imágenes actuales son temporales hasta incorporar el portfolio real del estudio.' },
  insights: { eyebrow: 'CURSOS DE DISEÑO MOBILIARIO', title: 'Del diseño desde cero\na la presentación final.', intro: 'Formación práctica en SketchUp, despiece, presupuesto y presentación para el cliente.', read: 'Ver contenido', by: 'Arq. Diana G. Piñanez', more: 'Más contenidos' },
  contact: { eyebrow: 'CONTACTO DIRECTO', title: 'Contame qué querés\ndiseñar o transformar.', intro: 'Casa nueva, reforma, ampliación, mobiliario, planos municipales o cursos.', studio: 'Estudio', place: 'Paraguay', hours: 'Atención con coordinación previa', visit: 'Consultas y reuniones con coordinación previa.', formTitle: 'Hablemos.', formIntro: 'Dejá tus datos y contame brevemente qué necesitás.', name: 'Nombre y apellido', email: 'Correo electrónico', phone: 'Teléfono', subject: '¿Qué necesitás?', message: 'Mensaje', placeholder: 'Contame sobre tu proyecto o curso de interés', submit: 'Enviar consulta', note: 'Próximamente conectaremos este formulario con el canal de contacto del estudio.', success: 'Gracias por tu consulta.', successText: 'Recibimos los datos del formulario.', edit: 'Editar mensaje', direct: 'Contacto directo', directText: 'Consultá por diseño de vivienda, reformas, mobiliario, planos municipales o cursos.' },
  cta: { label: '¿TENÉS UN PROYECTO EN MENTE?', title: 'Hagamos espacio\npara tu idea.', text: 'Contame qué necesitás y coordinamos una primera conversación.' },
  footer: { description: 'Arq. Diana G. Piñanez\nEstudio de arquitectura en Paraguay.', explore: 'Explorar', find: 'Ubicación', location: 'Paraguay', note: '© 2026 Arq. Diana G. Piñanez. Todos los derechos reservados.', privacy: 'Privacidad', privacyTitle: 'Privacidad', privacyText: 'Sitio web oficial del estudio de la Arq. Diana G. Piñanez.' },
  notFound: { title: 'Esta página no está disponible.', text: 'Volvé al inicio para seguir navegando.', button: 'Volver al inicio' }
 }
};
export const paths = ['', '/about', '/services', '/projects', '/insights', '/contact'];
export function pageMetadata(locale, index) {
 const c = copy[locale] || copy.es;
 return { title: `${c.nav[index]} | Arq. Diana G. Piñanez`, description: [c.home.intro,c.about.intro,c.services.intro,c.projects.intro,c.insights.intro,c.contact.intro][index], alternates: { languages: { es: sitePath(`/es${paths[index]}/`) } } };
}
